[package]
name = "result-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.74", features = ["full"] }

[lib]
proc-macro = true
